apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend-users.configMapName" . }}
  labels:
    {{- include "frontend-users.labels" . | nindent 4 }}
data:
  VITE_API_BASE_URL: {{ .Values.config.apiBaseUrl | quote }}
  VITE_API_USER_ORIGIN: {{ .Values.config.apiBaseUrl | quote }}
