apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-users.fullname" . }}
  labels:
    {{- include "frontend-users.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frontend-users.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend-users.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend-users
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "frontend-users.configMapName" . }}
                  key: VITE_API_BASE_URL
            - name: VITE_API_USER_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "frontend-users.configMapName" . }}
                  key: VITE_API_USER_ORIGIN
            - name: API_PROXY_TARGET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "frontend-users.configMapName" . }}
                  key: API_PROXY_TARGET
            {{- range .Values.env.additional }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
