{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "frontend-users.fullname" . }}
  labels:
    {{- include "frontend-users.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  to:
    kind: Service
    name: {{ include "frontend-users.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  tls:
    termination: {{ .Values.route.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.insecurePolicy }}
{{- end }}
